type: grasp_agent
record_dir: ./outputs/genesis/grasp
max_retry: 5
reset_mode: never
record_execute: true
stage: rl
horizon: 1000
rl_policy: runner
bc_policy: bc
run_demo_after_episode: true
env:
  type: genesis_grasp
  video_fmt: mp4
  seed: 7
  reset_time: 0
  example_root: /Users/tongmeng/Desktop/codes/genesis-world/examples/manipulation
  log_dir: /Users/tongmeng/Desktop/codes/genesis-world/examples/manipulation/logs/grasp_rl
  backend: cpu
  stage: rl
  show_viewer: true
  num_envs: 1
  box_fixed: false
  visualize_camera: true
  max_episode_steps: 1000000
policies:
  runner:
    type: rsl_rl
    log_dir: /Users/tongmeng/Desktop/codes/genesis-world/examples/manipulation/logs/grasp_rl
    train_cfg_index: 3
  bc:
    type: genesis_behavior_cloning
    example_root: /Users/tongmeng/Desktop/codes/genesis-world/examples/manipulation
    log_dir: /Users/tongmeng/Desktop/codes/genesis-world/examples/manipulation/logs/grasp_bc
    bc_cfg_index: 4
server:
  agent_name: 七仔
  agent_id: cap
  host: 127.0.0.1
  port: 8907
  skill_folder: skills
